config/routes.rb
Myapp::Application.routes.draw do

  resources :plantilla_correos
  resources :configuraciones
  resources :referencias
  get '/mi_horario', to: 'horarios#mi_horario'
  get '/usuarios/registrar', to: 'usuarios#registrar'

  post '/usuarios/guardar', to: 'usuarios#guardar'

  get '/usuarios/editar/:id', to: 'usuarios#editar'

  post '/usuarios/modificar', to: 'usuarios#modificar'

  get '/usuarios/cambiar_clave', to: 'usuarios#cambiar_clave'

  post '/usuarios/cambiar_clave', to: 'usuarios#confirmar_clave'

  delete '/usuarios/eliminar/:id', to: 'usuarios#eliminar'

  get 'grafico/tiempo_atencion'

  post 'grafico/tiempo_atencion', to: 'grafico#generar_tiempo_atencion'

  get 'grafico/tiempo_recepcion'

  post 'grafico/tiempo_recepcion', to: 'grafico#generar_tiempo_recepcion'

  get 'grafico/citas_por_turno'

  post 'grafico/citas_por_turno', to: 'grafico#generar_citas_por_turno'

  get 'grafico/satisfaccion_pacientes'

  post 'grafico/satisfaccion_pacientes', to: 'grafico#generar_satisfaccion_pacientes'

  get 'grafico/citas_solicitadas'

  post 'grafico/citas_solicitadas', to: 'grafico#generar_citas_solicitadas'

  get '/difusiones/update_entidades', to: 'difusiones#update_entidades'

  get '/grafico/update_entidades', to: 'grafico#update_entidades'

  get '/grafico/update_eventos', to: 'grafico#update_eventos'

  get '/grafico/update_servicios', to: 'grafico#update_servicios'

  get '/servicios/update_especialistas', to: 'servicios#update_especialistas'

  get '/grafico/update_servicios_por_especialidad', to: 'grafico#update_servicios_por_especialidad'

  get 'grafico/motivos_cancelacion'

  post 'grafico/motivos_cancelacion', to: 'grafico#generar_motivos_cancelacion'

  resources :suscriptores
  resources :medio_difusiones
  resources :perfiles
  resources :tipo_especialidades
  resources :rango_pesos
  resources :rango_edades
  resources :difusiones
  resources :tipo_entidades
  resources :parentescos
  resources :tipo_parentescos
  resources :tipo_difusiones

  post 'usuarios/create', to: 'usuarios#create'

get 'tipo_servicios/filtrar', to: 'tipo_servicios#filtrar'
  get 'perfil', to: 'usuarios#perfil'

  post 'perfil', to: 'usuarios#actualizarPerfil'

  get 'disponibilidad', to: 'horarios#disponibilidad'

  match '/search', to: "personas#search", via: "post"
  match 'grafico/calificaciones_por_criterio', to: "grafico#generar_citas_evaluadas", via: "post"
  match 'grafico/calificaciones_por_especialidad', to: "grafico#calcular_calificaciones_por_especialidad", via: "post"
  match 'grafico/citas_por_evento', to: "grafico#calcular_citas_por_evento", via: "post"
  match 'grafico/citas_por_difusion', to: "grafico#calcular_citas_por_difusion", via: "post"
  match 'grafico/calificaciones_por_servicio', to: "grafico#calcular_calificaciones_por_servicio", via: "post"
  match 'grafico/citas_por_turno', to: "grafico#generar_citas_por_turno", via: "post"
  match 'grafico/satisfaccion_pacientes', to: "grafico#generar_satisfaccion_pacientes", via: "post"
  match 'grafico/citas_por_caracteristicas', to: "grafico#generar_citas_caracteristicas", via: "post"

  get 'grafico/generar'

  get 'grafico/citas_por_especialidad'

  get 'grafico/criterios_servicio'

  get 'grafico/citas_por_turno'

  get 'grafico/reporte_por_criterios'
  get 'grafico/calificaciones_por_criterio'
  get 'grafico/calificaciones_por_especialidad'
  get 'grafico/citas_por_evento'
  get 'grafico/citas_por_difusion'
  get 'grafico/calificaciones_por_servicio'
  get 'grafico/citas_por_caracteristicas'

  get 'agenda_servicio/', to: 'agenda_servicio#lista'

  get 'historial_cita', to: 'citas#historial'

  get 'cancelar_cita', to: 'citas#cancelar'
  get 'cancelar_cita/:id', to: 'citas#cancelarCita'
  post 'cancelar_cita', to: 'citas#confirmarCancelacion'

  put 'cancelar_movil/:id', to: 'citas#cancelar_movil'

  get 'chequear_cita', to: 'citas#chequear'
  get 'chequear_cita/:id', to: 'citas#chequearCita'
  post 'chequear_cita', to: 'citas#guardarChequearCita'

  get 'finalizar_cita', to: 'citas#finalizar'
  get 'finalizar_cita/:id', to: 'citas#finalizarCita'
  post 'finalizar_cita', to: 'citas#guardarFinalizarCita'

  get 'historico', to: 'bd_admins#historico'
  post 'finalizar_migracion', to: 'bd_admins#cambiarInformacion'

  get 'guardarback', to: 'bd_admins#guardarback'
  post 'guardarback', to: 'bd_admins#guardarback'

  get 'restauracion', to: 'bd_admins#restauration'
  post 'restauracion', to: 'bd_admins#restauration'

  get 'evaluar_cita/:id', to: 'evaluaciones#evaluarCita', as: "evaluar_cita"
  resources :tipo_turnos

  get 'cerrar_turno/:id', to: 'horarios#cerrar_turno'

  resources :informacion_generals
  resources :noticias
  resources :opiniones
  resources :tipo_opiniones
  resources :tipo_preguntas
  resources :tipo_noticias
  get 'usuarios', to: 'usuarios#index'
  get 'solicitante/:id', to: 'usuarios#solicitante'

  get 'agenda_servicio/:id/detalle', to: 'agenda_servicio#detalle', as: :agenda_servicio_detalle

  resources :notificaciones
  resources :tipo_notificaciones
  resources :servicio_eventos
  resources :tipo_preguntas
  resources :tipo_opiniones
  resources :tipo_noticias
  resources :preguntas
  resources :opiniones
  resources :noticias
  resources :universidades
  resources :formacion_academicas
  resources :nivel_formaciones
  resources :eventos
  resources :tipo_eventos
  resources :busquedas
  resources :tipo_busquedas
  resources :categorias
  resources :citas
  resources :evaluaciones
  resources :criterio_tipo_servicios
  resources :calificaciones
  resources :criterios
  resources :servicios
  resources :sexos
  resources :personas
  resources :roles
  devise_for :usuarios , :controllers => {registrations: "usuarios/registrations", sessions: "usuarios/sessions", confirmations: 'usuarios/confirmations'}

  devise_scope :usuario do
    get 'login', to: 'usuarios/sessions#new'

    authenticated :usuario do
      root to: 'home#index', as: :authenticated_root
    end

  end
  get 'login_movil', to: 'usuarios#login_movil'
  get 'login_web', to: 'usuarios#login_web'
  get 'encontrar_usuario', to: 'usuarios#encontrar_por_email'

  root to: 'usuarios/sessions#new'

  resources :eventualidades
  resources :turnos
  resources :horarios
  resources :dias
  resources :tipo_criterios
  resources :tipo_horarios
  resources :tipo_citas
  resources :tipo_criterio
  resources :tipo_calificaciones
  resources :tipo_evaluaciones
  resources :tipo_pagos
  resources :tipo_eventualidades
  resources :motivos
  resources :tipo_motivos
  resources :tipo_servicios
  resources :tipo_atenciones
  resources :especialistas
  resources :especialidades
  resources :ubicaciones
  resources :sectores
  resources :sectors
  resources :tipo_ubicaciones
  resources :ciudades
  resources :estados
  resources :paises
  resources :discapacidades
  resources :tipo_discapacidades
  resources :patologias
  resources :tipo_patologias
  resources :vacunas
  resources :adicciones
  resources :tipo_adicciones
  resources :grupo_sanguineos
  resources :cirugias
  resources :tipo_cirugias
  resources :estado_civiles
  resources :ocupaciones
  resources :profesiones
  resources :lesiones
  resources :tipo_lesiones
  resources :habitos
  resources :tipo_habitos
  resources :option_menus

  get "home/index"
  get "home/minor"

  resources :preguntas
  resources :encuestas
end

app/controllers/difusiones_controller.rb
class DifusionesController < ApplicationController
  before_action :set_difusion, only: [:show, :edit, :update, :destroy]

  # GET /difusiones
  # GET /difusiones.json
  def index
    @difusiones = Difusion.where(:estatus => 1)
  end

  # GET /difusiones/1
  # GET /difusiones/1.json
  def show
  end

  # GET /difusiones/new
  def new
    @difusion = Difusion.new
    @tipo_entidades = TipoEntidad.where(:estatus => 1)
    @tipo_difusiones = TipoDifusion.where(:estatus => 1)
    @entidades = Servicio.where(:estatus => 1)
    @medios = MedioDifusion.where(:estatus => 1)
  end

  # GET /difusiones/1/edit
  def edit
    @tipo_entidades = TipoEntidad.where(:estatus => 1)
    @tipo_difusiones = TipoDifusion.where(:estatus => 1)
    if(@difusion.tipo_entidad_id == 1)
      @entidades = Servicio.where(:estatus => 1)
    else
      @entidades = Evento.where(:estatus => 1)
    end
    @medios = MedioDifusion.where(:estatus => 1)
  end

  # POST /difusiones
  # POST /difusiones.json
  def create
    @difusion = Difusion.new(difusion_params)
    @difusion.difusionesMedioDifusion = params[:medios]

    respond_to do |format|
      if @difusion.save
        if @difusion.tipo_difusion_id == 1 
          if @difusion.medio_difusiones.include?(MedioDifusion.find(1)) #email
            if(@difusion.tipo_entidad_id == 1)
              @tipoServicio = Servicio.find(@difusion.entidad_id).tipo_servicio
              @tipoServicio.difundirGeneral(@difusion)
            else
              @tipoServicios = Evento.find(@difusion.entidad_id).tipo_servicios
              @tipoServicios.each do |tipoServicio|
                tipoServicio.difundirGeneral(@difusion)
              end
            end  
          end

          if @difusion.medio_difusiones.include?(MedioDifusion.find(2)) #fb
            if(@difusion.tipo_entidad_id == 1)
              @servicio = Servicio.find(@difusion.entidad_id)
              @servicio.postearFb(@difusion)
            else
              @evento = Evento.find(@difusion.entidad_id)
              @evento.postearFb(@difusion)
            end  
          end

          if @difusion.medio_difusiones.include?(MedioDifusion.find(3)) #notificacion movil
            if(@difusion.tipo_entidad_id == 1)
              @tipoServicio = Servicio.find(@difusion.entidad_id).tipo_servicio
              @tipoServicio.notificarGeneral(@difusion)
            else
              @tipoServicios = Evento.find(@difusion.entidad_id).tipo_servicios
              @tipoServicios.each do |tipoServicio|
                tipoServicio.notificarGeneral(@difusion)
              end
            end  
          end
        else
          if @difusion.medio_difusiones.include?(MedioDifusion.find(1)) #email
            if(@difusion.tipo_entidad_id == 1)
              @tipoServicio = Servicio.find(@difusion.entidad_id).tipo_servicio
              @tipoServicio.difundirSegmentado(@difusion)
            else
              @tipoServicios = Evento.find(@difusion.entidad_id).tipo_servicios
              @tipoServicios.each do |tipoServicio|
                tipoServicio.difundirSegmentado(@difusion)
              end
            end  
          end

          if @difusion.medio_difusiones.include?(MedioDifusion.find(2)) #fb
            if(@difusion.tipo_entidad_id == 1)
              @servicio = Servicio.find(@difusion.entidad_id)
              @servicio.postearFb(@difusion)
            else
              @evento = Evento.find(@difusion.entidad_id)
              @evento.postearFb(@difusion)
            end  
          end

          if @difusion.medio_difusiones.include?(MedioDifusion.find(3)) #notificacion movil
            if(@difusion.tipo_entidad_id == 1)
              @tipoServicio = Servicio.find(@difusion.entidad_id).tipo_servicio
              @tipoServicio.notificarSegmentado(@difusion)
            else
              @tipoServicios = Evento.find(@difusion.entidad_id).tipo_servicios
              @tipoServicios.each do |tipoServicio|
                tipoServicio.notificarSegmentado(@difusion)
              end
            end  
          end
        end
        
        
        
        format.html { redirect_to difusiones_path, notice: 'El registro ha sido creado exitosamente.' }
        format.json { render :show, status: :created, location: @difusion }
      else
        format.html { render :new }
        format.json { render json: @difusion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /difusiones/1
  # PATCH/PUT /difusiones/1.json
  def update
    @difusion.difusionesMedioDifusion = params[:medios]
    respond_to do |format|
      if @difusion.update(difusion_params)
        format.html { redirect_to difusiones_path, info: 'El registro ha sido actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @difusion }
      else
        format.html { render :edit }
        format.json { render json: @difusion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /difusiones/1
  # DELETE /difusiones/1.json
  def destroy
    @difusion.estatus = 2
    @difusion.save
    respond_to do |format|
      format.html { redirect_to difusiones_path, alert: 'El registro ha sido eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  def update_entidades

    if (params[:tipo_entidad_id].to_i == 1)
      @entidades = Servicio.where(:estatus => 1)
    else
      @entidades = Evento.where(:estatus => 1)
    end
    respond_to do |format|
      format.js
      render 'difusiones/update_entidades'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_difusion
      @difusion = Difusion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def difusion_params
      params.require(:difusion).permit(:asunto, :texto, :imagen, :tipo_entidad_id, :entidad_id, :token_facebook, :tipo_difusion_id, :estatus, :avatar)
    end
end

app/helpers/difusiones_helper.rb
module DifusionesHelper
end

app/views/difusiones/_entidad.html.erb
<option value="<%= entidad.id %>"><%= entidad.descripcion %></option>

app/views/difusiones/_form.html.erb
<br>
<div class="row">   
   <div class="col-lg-10 col-lg-offset-1">
          <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h2 class="parametros-titulo"><%= "Difusión" %></h2>
              </div>
          </div>
          <div class="ibox-content">

          <%= form_for @difusion, :html => {:class => 'form-horizontal', :multipart => true } do |f| %>
                  <% if @difusion.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@difusion.errors.count, "error") %> prohibited this parametro from being saved:</h2>

                      <ul>
                      <% @difusion.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>

              <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#datos">Difusión</a></li>
                <li><a data-toggle="tab" href="#texto">Texto</a></li>
              </ul>

              <div class="tab-content">

                <div id="datos" class="tab-pane fade in active">
                  <br>
                  <div class="field form-group">
                    <label class="col-lg-2 control-label">Tipo de Difusión</label>
                    <div class="col-lg-10">
                      <%= f.collection_select(:tipo_difusion_id, @tipo_difusiones, :id, :descripcion, {},{:class => "form-control"}) %>
                    </div>
                    
                  </div>

                  <div class="field form-group">
                    <label class="col-lg-2 control-label">Tipo de Entidad</label>
                    <div class="col-lg-10">
                      <%= f.collection_select(:tipo_entidad_id, @tipo_entidades, :id, :descripcion, {},{:class => "form-control"}) %>
                    </div>
                    
                  </div>
                  

                  <div class="field form-group">
                    <label class="col-lg-2 control-label">Entidad</label>
                    <div class="col-lg-10">
                      <%= f.collection_select(:entidad_id, @entidades, :id, :descripcion, {},{:class => "form-control"}) %>
                    </div>
                    
                  </div>

                  <div class="field form-group">
                    <label class="col-lg-2 control-label">Medio de Difusión</label>
                    <div class="container-fluid col-lg-10">
                      <% if Configuracion.envia_email %>
                        <div class="col-sm-3">
                            <%= check_box_tag('medios[]', 1, (Configuracion.envia_email)) %> <%= MedioDifusion.find(1).descripcion %>
                        </div>
                      <% end %>
                      
                      <div class="col-sm-3">
                          <%= check_box_tag('medios[]', 2, (true)) %> <%= MedioDifusion.find(2).descripcion %>
                      </div>
                      <% if Configuracion.envia_notificaciones %>
                        <div class="col-sm-3">
                            <%= check_box_tag('medios[]', 3, (Configuracion.envia_notificaciones)) %> <%= MedioDifusion.find(3).descripcion %>
                        </div>
                      <% end %>
                  </div>
                    
                  </div>

                  <div class="form-group">
                      <label class="col-lg-2 control-label">Asunto</label>

                      <div class="col-lg-10"><%= f.text_field :asunto, :class => "form-control", :required => true %>
                       </div>
                    </div>

                   <div class="form-group">
                      <label class="col-lg-2 control-label">Foto</label>

                      <div class="col-lg-10"><%= f.file_field :avatar, :class => "form-control" %>
                       </div>
                    </div>
                </div>

                <div id="texto" class="tab-pane fade">
                  <br>
                  <div class="form-group">
                      <label class="col-lg-2 control-label">Texto</label>

                      <div class="col-lg-10"><%= f.text_area :texto, :class => "tinymce form-control" %>
                       </div>

                      <%= tinymce :language => "es_MX" %>
                    </div>
                </div>


              </div>

           
          <div class="form-group">
                      <div class="col-lg-offset-3 col-lg-2">
                           <%= f.submit "Guardar", :class => "btn btn-sm btn-primary" %>
                      </div>
                        <div class="col-lg-2">
                        <%= link_to 'Limpiar', '', type: :reset, :class => "btn btn-sm btn-warning " %>                          
                        </div>
                      <div class="col-lg-2">
                      <%= link_to 'Atras',difusiones_path, :class => "btn btn-sm btn-success" %>                          
                      </div>
                  </div>
                  
          <% end %>
          </div>
         
  </div>

</div>

app/views/difusiones/edit.html.erb
<br><br>

<%= render 'form', difusion: @difusion %>

app/views/difusiones/index.html.erb
<%= csrf_meta_tag %>
<br>
<div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h2 class="parametros-titulo"><%= "Difusiones" %></h2>
              </div>
          </div>
<div class="ibox-content">
<%= link_to 'Registrar', new_difusion_path, :class => "btn btn-primary btn-sm" %>
 <br><br> 

 <table class="footable table table-stripped" data-sorting="true" data-filtering="true">
    <thead>
      <tr>
        <th data-sorted="true">Tipo</th>
        <th data-breakpoints="xs">Asunto</th>
        <th data-breakpoints="xs">Entidad</th>
      </tr>
    </thead>
    <tbody>
      <% @difusiones.each do |difusion| %>
          <tr>
            <td><%= difusion.tipo_difusion.descripcion %></td>
            <td><%= difusion.asunto %></td>
            <td><%= difusion.entidad.descripcion%></td>            
          </tr>
      <% end %>
    </tbody>
      <tfoot>
        <tr>
            <td colspan="5">
                <ul class="pagination pull-right"></ul>
            </td>
        </tr>
      </tfoot>
  </table>
</div>
<br>


<script type="text/javascript">
$(document).ready(function(){
$('.table').footable();
});

</script>

app/views/difusiones/new.html.erb
<br><br>

<%= render 'form', difusion: @difusion %>

app/views/difusiones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asunto:</strong>
  <%= @difusion.asunto %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @difusion.texto %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @difusion.avatar %>
</p>

<p>
  <strong>Tipo entidad:</strong>
  <%= @difusion.tipo_entidad %>
</p>

<p>
  <strong>Entidad:</strong>
  <%= @difusion.entidad %>
</p>

<p>
  <strong>Token facebook:</strong>
  <%= @difusion.token_facebook %>
</p>

<p>
  <strong>Tipo difusion:</strong>
  <%= @difusion.tipo_difusion %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @difusion.estatus %>
</p>

<%= link_to 'Edit', edit_difusion_path(@difusion) %> |
<%= link_to 'Back', difusiones_path %>