config/routes.rb
Myapp::Application.routes.draw do

  resources :plantilla_correos
  resources :configuraciones
  resources :referencias
  get '/mi_horario', to: 'horarios#mi_horario'
  get '/usuarios/registrar', to: 'usuarios#registrar'

  post '/usuarios/guardar', to: 'usuarios#guardar'

  get '/usuarios/editar/:id', to: 'usuarios#editar'

  post '/usuarios/modificar', to: 'usuarios#modificar'

  get '/usuarios/cambiar_clave', to: 'usuarios#cambiar_clave'

  post '/usuarios/cambiar_clave', to: 'usuarios#confirmar_clave'

  delete '/usuarios/eliminar/:id', to: 'usuarios#eliminar'

  get 'grafico/tiempo_atencion'

  post 'grafico/tiempo_atencion', to: 'grafico#generar_tiempo_atencion'

  get 'grafico/tiempo_recepcion'

  post 'grafico/tiempo_recepcion', to: 'grafico#generar_tiempo_recepcion'

  get 'grafico/citas_por_turno'

  post 'grafico/citas_por_turno', to: 'grafico#generar_citas_por_turno'

  get 'grafico/satisfaccion_pacientes'

  post 'grafico/satisfaccion_pacientes', to: 'grafico#generar_satisfaccion_pacientes'

  get 'grafico/citas_solicitadas'

  post 'grafico/citas_solicitadas', to: 'grafico#generar_citas_solicitadas'

  get '/difusiones/update_entidades', to: 'difusiones#update_entidades'

  get '/grafico/update_entidades', to: 'grafico#update_entidades'

  get '/grafico/update_eventos', to: 'grafico#update_eventos'

  get '/grafico/update_servicios', to: 'grafico#update_servicios'

  get '/servicios/update_especialistas', to: 'servicios#update_especialistas'

  get '/grafico/update_servicios_por_especialidad', to: 'grafico#update_servicios_por_especialidad'

  get 'grafico/motivos_cancelacion'

  post 'grafico/motivos_cancelacion', to: 'grafico#generar_motivos_cancelacion'

  resources :suscriptores
  resources :medio_difusiones
  resources :perfiles
  resources :tipo_especialidades
  resources :rango_pesos
  resources :rango_edades
  resources :difusiones
  resources :tipo_entidades
  resources :parentescos
  resources :tipo_parentescos
  resources :tipo_difusiones

  post 'usuarios/create', to: 'usuarios#create'

get 'tipo_servicios/filtrar', to: 'tipo_servicios#filtrar'
  get 'perfil', to: 'usuarios#perfil'

  post 'perfil', to: 'usuarios#actualizarPerfil'

  get 'disponibilidad', to: 'horarios#disponibilidad'

  match '/search', to: "personas#search", via: "post"
  match 'grafico/calificaciones_por_criterio', to: "grafico#generar_citas_evaluadas", via: "post"
  match 'grafico/calificaciones_por_especialidad', to: "grafico#calcular_calificaciones_por_especialidad", via: "post"
  match 'grafico/citas_por_evento', to: "grafico#calcular_citas_por_evento", via: "post"
  match 'grafico/citas_por_difusion', to: "grafico#calcular_citas_por_difusion", via: "post"
  match 'grafico/calificaciones_por_servicio', to: "grafico#calcular_calificaciones_por_servicio", via: "post"
  match 'grafico/citas_por_turno', to: "grafico#generar_citas_por_turno", via: "post"
  match 'grafico/satisfaccion_pacientes', to: "grafico#generar_satisfaccion_pacientes", via: "post"
  match 'grafico/citas_por_caracteristicas', to: "grafico#generar_citas_caracteristicas", via: "post"

  get 'grafico/generar'

  get 'grafico/citas_por_especialidad'

  get 'grafico/criterios_servicio'

  get 'grafico/citas_por_turno'

  get 'grafico/reporte_por_criterios'
  get 'grafico/calificaciones_por_criterio'
  get 'grafico/calificaciones_por_especialidad'
  get 'grafico/citas_por_evento'
  get 'grafico/citas_por_difusion'
  get 'grafico/calificaciones_por_servicio'
  get 'grafico/citas_por_caracteristicas'

  get 'agenda_servicio/', to: 'agenda_servicio#lista'

  get 'historial_cita', to: 'citas#historial'

  get 'cancelar_cita', to: 'citas#cancelar'
  get 'cancelar_cita/:id', to: 'citas#cancelarCita'
  post 'cancelar_cita', to: 'citas#confirmarCancelacion'

  put 'cancelar_movil/:id', to: 'citas#cancelar_movil'

  get 'chequear_cita', to: 'citas#chequear'
  get 'chequear_cita/:id', to: 'citas#chequearCita'
  post 'chequear_cita', to: 'citas#guardarChequearCita'

  get 'finalizar_cita', to: 'citas#finalizar'
  get 'finalizar_cita/:id', to: 'citas#finalizarCita'
  post 'finalizar_cita', to: 'citas#guardarFinalizarCita'

  get 'historico', to: 'bd_admins#historico'
  post 'finalizar_migracion', to: 'bd_admins#cambiarInformacion'

  get 'guardarback', to: 'bd_admins#guardarback'
  post 'guardarback', to: 'bd_admins#guardarback'

  get 'restauracion', to: 'bd_admins#restauration'
  post 'restauracion', to: 'bd_admins#restauration'

  get 'evaluar_cita/:id', to: 'evaluaciones#evaluarCita', as: "evaluar_cita"
  resources :tipo_turnos

  get 'cerrar_turno/:id', to: 'horarios#cerrar_turno'

  resources :informacion_generals
  resources :noticias
  resources :opiniones
  resources :tipo_opiniones
  resources :tipo_preguntas
  resources :tipo_noticias
  get 'usuarios', to: 'usuarios#index'
  get 'solicitante/:id', to: 'usuarios#solicitante'

  get 'agenda_servicio/:id/detalle', to: 'agenda_servicio#detalle', as: :agenda_servicio_detalle

  resources :notificaciones
  resources :tipo_notificaciones
  resources :servicio_eventos
  resources :tipo_preguntas
  resources :tipo_opiniones
  resources :tipo_noticias
  resources :preguntas
  resources :opiniones
  resources :noticias
  resources :universidades
  resources :formacion_academicas
  resources :nivel_formaciones
  resources :eventos
  resources :tipo_eventos
  resources :busquedas
  resources :tipo_busquedas
  resources :categorias
  resources :citas
  resources :evaluaciones
  resources :criterio_tipo_servicios
  resources :calificaciones
  resources :criterios
  resources :servicios
  resources :sexos
  resources :personas
  resources :roles
  devise_for :usuarios , :controllers => {registrations: "usuarios/registrations", sessions: "usuarios/sessions", confirmations: 'usuarios/confirmations'}

  devise_scope :usuario do
    get 'login', to: 'usuarios/sessions#new'

    authenticated :usuario do
      root to: 'home#index', as: :authenticated_root
    end

  end
  get 'login_movil', to: 'usuarios#login_movil'
  get 'login_web', to: 'usuarios#login_web'
  get 'encontrar_usuario', to: 'usuarios#encontrar_por_email'

  root to: 'usuarios/sessions#new'

  resources :eventualidades
  resources :turnos
  resources :horarios
  resources :dias
  resources :tipo_criterios
  resources :tipo_horarios
  resources :tipo_citas
  resources :tipo_criterio
  resources :tipo_calificaciones
  resources :tipo_evaluaciones
  resources :tipo_pagos
  resources :tipo_eventualidades
  resources :motivos
  resources :tipo_motivos
  resources :tipo_servicios
  resources :tipo_atenciones
  resources :especialistas
  resources :especialidades
  resources :ubicaciones
  resources :sectores
  resources :sectors
  resources :tipo_ubicaciones
  resources :ciudades
  resources :estados
  resources :paises
  resources :discapacidades
  resources :tipo_discapacidades
  resources :patologias
  resources :tipo_patologias
  resources :vacunas
  resources :adicciones
  resources :tipo_adicciones
  resources :grupo_sanguineos
  resources :cirugias
  resources :tipo_cirugias
  resources :estado_civiles
  resources :ocupaciones
  resources :profesiones
  resources :lesiones
  resources :tipo_lesiones
  resources :habitos
  resources :tipo_habitos
  resources :option_menus

  get "home/index"
  get "home/minor"

  resources :preguntas
  resources :encuestas
end

app/models/bd_admin.rb
class BdAdmin < ApplicationRecord
end

app/controllers/bd_admins_controller.rb
class BdAdminsController < ApplicationController
  before_action :set_bd_admin, only: [:show, :edit, :update, :destroy]

  # GET /bd_admins
  # GET /bd_admins.json
  def index
    @bd_admins = BdAdmin.all
  end

  # GET /bd_admins/1
  # GET /bd_admins/1.json
  def show
  end

  # GET /bd_admins/new
  def new
    @bd_admin = BdAdmin.new
  end

  # GET /bd_admins/1/edit
  def edit
  end

  # POST /bd_admins
  # POST /bd_admins.json
  def create
    @bd_admin = BdAdmin.new(bd_admin_params)

    respond_to do |format|
      if @bd_admin.save
        format.html { redirect_to @bd_admin, notice: 'Bd admin was successfully created.' }
        format.json { render :show, status: :created, location: @bd_admin }
      else
        format.html { render :new }
        format.json { render json: @bd_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bd_admins/1
  # PATCH/PUT /bd_admins/1.json
  def update
    respond_to do |format|
      if @bd_admin.update(bd_admin_params)
        format.html { redirect_to @bd_admin, notice: 'Bd admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bd_admin }
      else
        format.html { render :edit }
        format.json { render json: @bd_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bd_admins/1
  # DELETE /bd_admins/1.json
  def destroy
    @bd_admin.destroy
    respond_to do |format|
      format.html { redirect_to bd_admins_url, notice: 'Bd admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def historico
    @BdAdmins = BdAdmin.new

    @stringnes = []

    if Servicio.count > 0
      @stringnes.push("Servicio")
    end
    if Cita.count > 0
      @stringnes.push("Cita")
    end
    if Especialista.count > 0
      @stringnes.push("Especialista")
    end
    if TipoServicio.count > 0
      @stringnes.push("Tipo Servicio")
    end 
    if Persona.count > 0
      @stringnes.push("Persona")
    end
    if Usuario.count > 0
      @stringnes.push("Usuario")
    end
    if Calificacion.count > 0
      @stringnes.push("Calificacion")
    end 
    if Difusion.count > 0
      @stringnes.push("Difusion")
    end
    if Opinion.count > 0
     @stringnes.push("Opinion")
    end

    #@stringnes = ["Servicio", "Cita", "Especialista", "Tipo Servicio", "Persona", "Usuario", "Calificacion", "Difusion", "Opinion"]
    
    render "historico_tablas"
  end

  def cambiarInformacion
    @tablas = params[:e1]
    #puts params['Inactivo'].nil?
    #puts params['Activo'].nil?
    #puts params['BdAdmin']['fecha_inicio(1i)']
    #puts params['BdAdmin']['fecha_inicio(2i)']
    #puts params['BdAdmin']['fecha_inicio(3i)']
    
    @d = Date.new(params['BdAdmin']['fecha_inicio(1i)'].to_i,params['BdAdmin']['fecha_inicio(2i)'].to_i,params['BdAdmin']['fecha_inicio(3i)'].to_i)
    @fecha = DateTime.new(@d.year, @d.month, @d.day,23,59,00)

    # Uno (1) representa quiere activos e inactivos, 2 solo activos, 3 incativos
    $decision = 1

    if params['Inactivo'] == "0" and params['Activo'] == "1"
      $decision = 1
      puts "Inactivo activo"
      puts $decision
    else
      if params['Inactivo'] == "0"
        puts "Inactivo"

         $decision = 2
         puts $decision
       else
        puts "Inactivo"
         $decision = 3
         puts $decision
      end
    end

    @tablas.each do |tabla|
      case tabla[0]
      when "Servicio"
        
        @servicios = Servicio.all

        @servicios.each do |servicio|
          his_servicio = HisServicio.new
          if  $decision == 1 and servicio.created_at.to_s(:number).to_i < @fecha.to_s(:number).to_i
              his_servicio.descripcion = servicio.descripcion
              his_servicio.ubicacion = servicio.ubicacion.id
              his_servicio.tipo_servicio = servicio.tipo_servicio.id
              his_servicio.especialista = servicio.especialista.id
              his_servicio.estatus = servicio.estatus
              his_servicio.precio = servicio.precio
              his_servicio.save          
          else
            if $decision == 2 and servicio.estatus == 2 and servicio.created_at.to_s(:number).to_i < @fecha.to_s(:number).to_i
              his_servicio.descripcion = servicio.descripcion
              his_servicio.ubicacion = servicio.ubicacion.id
              his_servicio.tipo_servicio = servicio.tipo_servicio.id
              his_servicio.especialista = servicio.especialista.id
              his_servicio.estatus = servicio.estatus
              his_servicio.precio = servicio.precio
              his_servicio.save    
            else
              if $decision == 3 and servicio.created_at.to_s(:number).to_i < @fecha.to_s(:number).to_i
              his_servicio.descripcion = servicio.descripcion
              his_servicio.ubicacion = servicio.ubicacion.id
              his_servicio.tipo_servicio = servicio.tipo_servicio.id
              his_servicio.especialista = servicio.especialista.id
              his_servicio.estatus = servicio.estatus
              his_servicio.precio = servicio.precio
              his_servicio.save 
                 end #end del if
                end #end del for
               end
               servicio.destroy
              end
      when "Cita"
        
        @citas = Cita.all
        @citas.each do |cita|
          his_cita = HisCita.new
          if $decision == 1 and cita.created_at.to_s(:number).to_i < @fecha.to_s(:number).to_i
              his_cita.turno = cita.turno.id
              his_cita.persona = cita.persona.id
              his_cita.usuario = cita.usuario.id
              his_cita.fecha = cita.fecha
              his_cita.tipo_pago = cita.tipo_pago.id
              his_cita.eventualidad = cita.eventualidad.id
              his_cita.estatus = cita.estatus
              his_cita.save          
          else 
            if $decision == 2 and cita.estatus == 5 and cita.created_at.to_s(:number).to_i < @fecha.to_s(:number).to_i
              his_cita.turno = cita.turno.id
              his_cita.persona = cita.persona.id
              his_cita.usuario = cita.usuario.id
              his_cita.fecha = cita.fecha
              his_cita.tipo_pago = cita.tipo_pago.id
              his_cita.eventualidad = cita.eventualidad.id
              his_cita.estatus = cita.estatus
              his_cita.save          
            else
              if $decision == 3 and cita.estatus == 1 and cita.created_at.to_s(:number).to_i < @fecha.to_s(:number).to_i
              his_cita.turno = cita.turno.id
              his_cita.persona = cita.persona.id
              his_cita.usuario = cita.usuario.id
              his_cita.fecha = cita.fecha
              his_cita.tipo_pago = cita.tipo_pago.id
              his_cita.eventualidad = cita.eventualidad.id
              his_cita.estatus = cita.estatus
              his_cita.save          
               end #end del if
                 #Agregar cascades y permitir el metodo de abajo sino lanza error
              end #end del for
             end
             cita.destroy
            end
      when "Especialista"
        
        @especialistas = Especialista.all
        @especialistas.each do |especialista|
          his_especialista = HisEspecialista.new
          if $decision == 1 and especialista.created_at.to_s(:number).to_i < @fecha.to_s(:number).to_i
                #his_especialista.universidad = especialista.universidad.id
                #his_especialista.formacion_academica = especialista.formacion_academica.id
                his_especialista.persona = especialista.persona.id
                his_especialista.estatus = especialista.estatus
                his_especialista.save          
          else
            if $decision == 2 and especialista.estatus == 2 and especialista.created_at.to_s(:number).to_i < @fecha.to_s(:number).to_i
                #his_especialista.universidad = especialista.universidad.id
                #his_especialista.formacion_academica = especialista.formacion_academica.id
                his_especialista.persona = especialista.persona.id
                his_especialista.estatus = especialista.estatus
                his_especialista.save            
            else
              if $decision == 3 and especialista.estatus == 1 and especialista.created_at.to_s(:number).to_i < @fecha.to_s(:number).to_i
                #his_especialista.universidad = especialista.universidad.id
                #his_especialista.formacion_academica = especialista.formacion_academica.id
                his_especialista.persona = especialista.persona.id
                his_especialista.estatus = especialista.estatus
                his_especialista.save               
               end #end del if
                 #Agregar cascades y permitir el metodo de abajo sino lanza error
                 
              end #end del for
             end

             $services = Servicio.where(:especialista => especialista.id)
             $services.each do |serv|
                puts 'Soy un servicio violento'
                serv.destroy
             end

             #este tambien destruye al especialista

             $peer = Persona.find(especialista.persona.id)

             $peer.destroy


            end
      when "Tipo Servicio"
        
        @tipos_servicios = TipoServicio.all
        @tipos_servicios.each do |tipo_servicio|
          his_tipoServicio = HisTipoServicio.new
          if $decision == 1 and tipo_servicio.created_at.to_s(:number).to_i < @fecha.to_s(:number).to_i
                his_tipoServicio.descripcion = tipo_servicio.descripcion
                his_tipoServicio.texto = tipo_servicio.texto
                his_tipoServicio.estatus = tipo_servicio.estatus
                his_tipoServicio.categoria = tipo_servicio.categoria.id
                his_tipoServicio.especialidad = tipo_servicio.especialidad.id
                his_tipoServicio.tipo_atencion = tipo_servicio.tipo_atencion.id

app/views/bd_admins/_form.html.erb
<%= form_for(bd_admin) do |f| %>
  <% if bd_admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bd_admin.errors.count, "error") %> prohibited this bd_admin from being saved:</h2>

      <ul>
      <% bd_admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :historico %>
    <%= f.text_field :historico %>
  </div>

  <div class="field">
    <%= f.label :hora_backup %>
    <%= f.datetime_select :hora_backup %>
  </div>

  <div class="field">
    <%= f.label :opcion_estatus %>
    <%= f.number_field :opcion_estatus %>
  </div>

  <div class="field">
    <%= f.label :fecha_inicio %>
    <%= f.datetime_select :fecha_inicio %>
  </div>

  <div class="field">
    <%= f.label :estatus %>
    <%= f.number_field :estatus %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bd_admins/backup_tablas.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
  <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h2 class="parametros-titulo"><%= "Ordenar Backup de Base de Datos" %></h2>
              </div>
          </div>
    <div class="ibox-content">
      <%= form_tag "/guardarback", method: "post", :html => {:class => 'form-horizontal'} do |f| %>

  <br> 
            <br> <br>

          <div class="col-sm-6 ">
                <spam>Generar un respaldo de base de datos ahora</spam>
          </div>

          <div class="col-sm-6 ">

          <%= submit_tag 'Generar', :class => "btn btn-sm btn-primary"  %>

          </div>

          <br><br><br><br>

          <div class="row">

          <div class="col-sm-6 ">
                <spam>Generar o programar un respaldo en la nube Amazon S3</spam>
          </div>

          <div class="col-sm-6 ">

          <%= link_to "DUMPER", "http://dumper.io/", target: "_blank", class: 'btn btn-sm btn-info' %>

          </div>

          </div>

          <% end %>
    </div>
  </div>
</div>

app/views/bd_admins/edit.html.erb
<h1>Editing Bd Admin</h1>

<%= render 'form', bd_admin: @bd_admin %>

<%= link_to 'Show', @bd_admin %> |
<%= link_to 'Back', bd_admins_path %>

app/views/bd_admins/historico_tablas.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
  <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h2 class="parametros-titulo"><%= "Historico de Base de Datos" %></h2>
              </div>
          </div>
    <div class="ibox-content">
      <%= form_tag "/finalizar_migracion", method: "post", :html => {:class => 'form-horizontal'} do |f| %>

            <script>
              $(document).ready(function() { $("#e1_").select2(); });
            </script>

            <%= select("e1", nil, @stringnes, { include_blank: false }, html_options = {:multiple => "multiple", :style => "width: 800px"}) %>

            <br> <br> 

              <div class="row">
              <div class="col-sm-6 ">
                  <spam>Seleccione la fecha hasta la cual requiere que se migre la informacion:</spam>
              </div>
              <div class="col-sm-6 ">
                  <%= date_select("BdAdmin", "fecha_inicio", min: 50.year.ago, end_year: Time.now.year) %>
              </div>
              </div>

            <br> <br>

            <div class="row">
               <div class="col-sm-6 "></div>
               <div class="col-sm-6 "></div>
            </div>
            
            <p>Seleccione el estatus de los registros que desea migrar:</p>
            <div id="estatus_guardado" class="tab-pane fade in">
              <div class="container-fluid">
              <div class="row">
              <div class="col-sm-3 ">
              <spam>Activo</spam>
              </div>
                  <div class="col-sm-3 ">
                    <%= check_box_tag 'Activo', 1, false %> 
                  </div>
              </div>
              <div class="row">
              <div class="col-sm-3 ">
              <spam>Inactivo</spam>
              </div>
                  <div class="col-sm-3 ">
                    <%= check_box_tag 'Inactivo', 0, true %>
                  </div>
              </div>
              </div>  
            </div>



          <div class="form-group row">
              <div class="col-lg-offset-3 col-lg-2">
                  <%= submit_tag 'Guardar', :class => "btn btn-sm btn-primary"  %>
              </div>
              <div class="col-lg-2">
              <%= link_to 'Volver', '/chequear_cita', :class => "btn btn-sm btn-success", :title => "Atras" %>                          
              </div>
          </div>




            <% end %>
    </div>
  </div>
</div>

app/views/bd_admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bd Admins</h1>

<table>
  <thead>
    <tr>
      <th>Historico</th>
      <th>Hora backup</th>
      <th>Opcion estatus</th>
      <th>Fecha inicio</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bd_admins.each do |bd_admin| %>
      <tr>
        <td><%= bd_admin.historico %></td>
        <td><%= bd_admin.hora_backup %></td>
        <td><%= bd_admin.opcion_estatus %></td>
        <td><%= bd_admin.fecha_inicio %></td>
        <td><%= bd_admin.estatus %></td>
        <td><%= link_to 'Show', bd_admin %></td>
        <td><%= link_to 'Edit', edit_bd_admin_path(bd_admin) %></td>
        <td><%= link_to 'Destroy', bd_admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bd Admin', new_bd_admin_path %>

app/views/bd_admins/new.html.erb
<h1>New Bd Admin</h1>

<%= render 'form', bd_admin: @bd_admin %>

<%= link_to 'Back', bd_admins_path %>

app/views/bd_admins/restore_tablas.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
  <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h2 class="parametros-titulo"><%= "Orden de Restauracion de Base de Datos" %></h2>
              </div>
          </div>
    <div class="ibox-content">
      <%= form_tag "/restauracion", method: "post", :html => {:class => 'form-horizontal'} do |f| %>
          

          <div class="form-group">
            <label class="col-lg-5 control-label">Seleccione el respaldo a utilizar</label>

            <div class="col-lg-7"><%= select_tag('foos', @f) %>
            </div>
          </div>

          <br> <br>

          <table class="table">
              <tr>
                <th><%= if !@obj.nil? then "Respaldo" else "y" end %></th>
                <th><%= if !@obj.nil? then "Fecha" else "z" end %></th>
                <th><%= if !@obj.nil? then "Numero de Respaldo" else "2" end %></th>
              </tr>
              <tr>
                <td><%= if @obj.nil? then "" else "Primero" end %></td>
                <td><%= if @obj.nil? then "" else @obj.fecha_inicio.to_s end %></td>
                <td><%= if @obj.nil? then "" else @obj.id.to_s end %></td>
              </tr>
              <tr>
                <td><%= if @obj2.nil? then "" else "Segundo" end %></td>
                <td><%= if @obj2.nil? then "" else @obj2.fecha_inicio.to_s end %></td>
                <td><%= if @obj2.nil? then "" else @obj2.id.to_s end %></td>
              </tr>
              <tr>
                <td><%= if @obj3.nil? then "" else "Tercero" end %></td>
                <td><%= if @obj3.nil? then "" else @obj3.fecha_inicio.to_s end %></td>
                <td><%= if @obj3.nil? then "" else @obj3.id.to_s end %></td>
              </tr>
          </table>
           <br> <br>

          <div class="form-group row">
              <div class="col-lg-offset-3 col-lg-2">
                  <%= submit_tag 'Generar', :class => "btn btn-sm btn-primary"  %>
              </div>
              <div class="col-lg-2">
              <%= link_to 'Volver', '/chequear_cita', :class => "btn btn-sm btn-success", :title => "Atras" %>                          
              </div>
          </div>

          <% end %>
    </div>
  </div>
</div>

app/views/bd_admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Historico:</strong>
  <%= @bd_admin.historico %>
</p>

<p>
  <strong>Hora backup:</strong>
  <%= @bd_admin.hora_backup %>
</p>

<p>
  <strong>Opcion estatus:</strong>
  <%= @bd_admin.opcion_estatus %>
</p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @bd_admin.fecha_inicio %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @bd_admin.estatus %>
</p>

<%= link_to 'Edit', edit_bd_admin_path(@bd_admin) %> |
<%= link_to 'Back', bd_admins_path %>