config/routes.rb
Myapp::Application.routes.draw do

  resources :plantilla_correos
  resources :configuraciones
  resources :referencias
  get '/mi_horario', to: 'horarios#mi_horario'
  get '/usuarios/registrar', to: 'usuarios#registrar'

  post '/usuarios/guardar', to: 'usuarios#guardar'

  get '/usuarios/editar/:id', to: 'usuarios#editar'

  post '/usuarios/modificar', to: 'usuarios#modificar'

  get '/usuarios/cambiar_clave', to: 'usuarios#cambiar_clave'

  post '/usuarios/cambiar_clave', to: 'usuarios#confirmar_clave'

  delete '/usuarios/eliminar/:id', to: 'usuarios#eliminar'

  get 'grafico/tiempo_atencion'

  post 'grafico/tiempo_atencion', to: 'grafico#generar_tiempo_atencion'

  get 'grafico/tiempo_recepcion'

  post 'grafico/tiempo_recepcion', to: 'grafico#generar_tiempo_recepcion'

  get 'grafico/citas_por_turno'

  post 'grafico/citas_por_turno', to: 'grafico#generar_citas_por_turno'

  get 'grafico/satisfaccion_pacientes'

  post 'grafico/satisfaccion_pacientes', to: 'grafico#generar_satisfaccion_pacientes'

  get 'grafico/citas_solicitadas'

  post 'grafico/citas_solicitadas', to: 'grafico#generar_citas_solicitadas'

  get '/difusiones/update_entidades', to: 'difusiones#update_entidades'

  get '/grafico/update_entidades', to: 'grafico#update_entidades'

  get '/grafico/update_eventos', to: 'grafico#update_eventos'

  get '/grafico/update_servicios', to: 'grafico#update_servicios'

  get '/servicios/update_especialistas', to: 'servicios#update_especialistas'

  get '/grafico/update_servicios_por_especialidad', to: 'grafico#update_servicios_por_especialidad'

  get 'grafico/motivos_cancelacion'

  post 'grafico/motivos_cancelacion', to: 'grafico#generar_motivos_cancelacion'

  resources :suscriptores
  resources :medio_difusiones
  resources :perfiles
  resources :tipo_especialidades
  resources :rango_pesos
  resources :rango_edades
  resources :difusiones
  resources :tipo_entidades
  resources :parentescos
  resources :tipo_parentescos
  resources :tipo_difusiones

  post 'usuarios/create', to: 'usuarios#create'

get 'tipo_servicios/filtrar', to: 'tipo_servicios#filtrar'
  get 'perfil', to: 'usuarios#perfil'

  post 'perfil', to: 'usuarios#actualizarPerfil'

  get 'disponibilidad', to: 'horarios#disponibilidad'

  match '/search', to: "personas#search", via: "post"
  match 'grafico/calificaciones_por_criterio', to: "grafico#generar_citas_evaluadas", via: "post"
  match 'grafico/calificaciones_por_especialidad', to: "grafico#calcular_calificaciones_por_especialidad", via: "post"
  match 'grafico/citas_por_evento', to: "grafico#calcular_citas_por_evento", via: "post"
  match 'grafico/citas_por_difusion', to: "grafico#calcular_citas_por_difusion", via: "post"
  match 'grafico/calificaciones_por_servicio', to: "grafico#calcular_calificaciones_por_servicio", via: "post"
  match 'grafico/citas_por_turno', to: "grafico#generar_citas_por_turno", via: "post"
  match 'grafico/satisfaccion_pacientes', to: "grafico#generar_satisfaccion_pacientes", via: "post"
  match 'grafico/citas_por_caracteristicas', to: "grafico#generar_citas_caracteristicas", via: "post"

  get 'grafico/generar'

  get 'grafico/citas_por_especialidad'

  get 'grafico/criterios_servicio'

  get 'grafico/citas_por_turno'

  get 'grafico/reporte_por_criterios'
  get 'grafico/calificaciones_por_criterio'
  get 'grafico/calificaciones_por_especialidad'
  get 'grafico/citas_por_evento'
  get 'grafico/citas_por_difusion'
  get 'grafico/calificaciones_por_servicio'
  get 'grafico/citas_por_caracteristicas'

  get 'agenda_servicio/', to: 'agenda_servicio#lista'

  get 'historial_cita', to: 'citas#historial'

  get 'cancelar_cita', to: 'citas#cancelar'
  get 'cancelar_cita/:id', to: 'citas#cancelarCita'
  post 'cancelar_cita', to: 'citas#confirmarCancelacion'

  put 'cancelar_movil/:id', to: 'citas#cancelar_movil'

  get 'chequear_cita', to: 'citas#chequear'
  get 'chequear_cita/:id', to: 'citas#chequearCita'
  post 'chequear_cita', to: 'citas#guardarChequearCita'

  get 'finalizar_cita', to: 'citas#finalizar'
  get 'finalizar_cita/:id', to: 'citas#finalizarCita'
  post 'finalizar_cita', to: 'citas#guardarFinalizarCita'

  get 'historico', to: 'bd_admins#historico'
  post 'finalizar_migracion', to: 'bd_admins#cambiarInformacion'

  get 'guardarback', to: 'bd_admins#guardarback'
  post 'guardarback', to: 'bd_admins#guardarback'

  get 'restauracion', to: 'bd_admins#restauration'
  post 'restauracion', to: 'bd_admins#restauration'

  get 'evaluar_cita/:id', to: 'evaluaciones#evaluarCita', as: "evaluar_cita"
  resources :tipo_turnos

  get 'cerrar_turno/:id', to: 'horarios#cerrar_turno'

  resources :informacion_generals
  resources :noticias
  resources :opiniones
  resources :tipo_opiniones
  resources :tipo_preguntas
  resources :tipo_noticias
  get 'usuarios', to: 'usuarios#index'
  get 'solicitante/:id', to: 'usuarios#solicitante'

  get 'agenda_servicio/:id/detalle', to: 'agenda_servicio#detalle', as: :agenda_servicio_detalle

  resources :notificaciones
  resources :tipo_notificaciones
  resources :servicio_eventos
  resources :tipo_preguntas
  resources :tipo_opiniones
  resources :tipo_noticias
  resources :preguntas
  resources :opiniones
  resources :noticias
  resources :universidades
  resources :formacion_academicas
  resources :nivel_formaciones
  resources :eventos
  resources :tipo_eventos
  resources :busquedas
  resources :tipo_busquedas
  resources :categorias
  resources :citas
  resources :evaluaciones
  resources :criterio_tipo_servicios
  resources :calificaciones
  resources :criterios
  resources :servicios
  resources :sexos
  resources :personas
  resources :roles
  devise_for :usuarios , :controllers => {registrations: "usuarios/registrations", sessions: "usuarios/sessions", confirmations: 'usuarios/confirmations'}

  devise_scope :usuario do
    get 'login', to: 'usuarios/sessions#new'

    authenticated :usuario do
      root to: 'home#index', as: :authenticated_root
    end

  end
  get 'login_movil', to: 'usuarios#login_movil'
  get 'login_web', to: 'usuarios#login_web'
  get 'encontrar_usuario', to: 'usuarios#encontrar_por_email'

  root to: 'usuarios/sessions#new'

  resources :eventualidades
  resources :turnos
  resources :horarios
  resources :dias
  resources :tipo_criterios
  resources :tipo_horarios
  resources :tipo_citas
  resources :tipo_criterio
  resources :tipo_calificaciones
  resources :tipo_evaluaciones
  resources :tipo_pagos
  resources :tipo_eventualidades
  resources :motivos
  resources :tipo_motivos
  resources :tipo_servicios
  resources :tipo_atenciones
  resources :especialistas
  resources :especialidades
  resources :ubicaciones
  resources :sectores
  resources :sectors
  resources :tipo_ubicaciones
  resources :ciudades
  resources :estados
  resources :paises
  resources :discapacidades
  resources :tipo_discapacidades
  resources :patologias
  resources :tipo_patologias
  resources :vacunas
  resources :adicciones
  resources :tipo_adicciones
  resources :grupo_sanguineos
  resources :cirugias
  resources :tipo_cirugias
  resources :estado_civiles
  resources :ocupaciones
  resources :profesiones
  resources :lesiones
  resources :tipo_lesiones
  resources :habitos
  resources :tipo_habitos
  resources :option_menus

  get "home/index"
  get "home/minor"

  resources :preguntas
  resources :encuestas
end

app/controllers/citas_controller.rb
  class CitasController < ApplicationController
  before_action :set_cita, only: [:show, :edit, :update, :destroy]

  # GET /citas
  # GET /citas.json
  def index
    if params[:persona].nil?
      @lista = Cita.where({:usuario_id => current_usuario.id, :estatus => 1})
    else
      @lista = Cita.where({:usuario_id => params[:persona]})
    end
      respond_to do |format|
      format.html
      format.json { render json: @lista }
    end
  end

  # GET /citas/1
  # GET /citas/1.json
  def show 
    if Cita.exists?(id: params[:id])
        @parametro = Cita.find(params[:id])
    else
      @parametro = Cita.new
    end
    respond_to do |format|
      if !@parametro.id.nil?
        format.html
        format.json { render json: @parametro.to_json }
      else
        format.json { render json: @cita.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /citas/new
  def new
    @cita = Cita.new
  end

  # GET /citas/1/edit
  def edit
  end

  # POST /citas
  # POST /citas.json
  def create
    @persona = Persona.where(:cedula => params[:paciente_cedula]).take
    @cita = Cita.new(cita_params)
    @cita.estatus = 1
    @cita.persona_id = @persona.id
    respond_to do |format|
      if @cita.save
        if Configuracion.envia_email
          ExampleMailer.cita_registrada(@cita).deliver_now
        end
        if Configuracion.envia_notificaciones
          Notificacion.create(descripcion:"Solicitud de cita.", mensaje: "Haz solicitado una cita para el servicio "+@cita.turno.horario.servicio.descripcion, url:"", usuario_id:@cita.usuario_id, tipo_notificacion_id: 1, entidad_id: @cita.id )
        end
        format.html { redirect_to @cita, notice: 'Cita was successfully created.' }
        format.json { render :show, status: :created, location: @cita }
      else
        format.html { render :new }
        format.json { render json: @cita.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /citas/1
  # PATCH/PUT /citas/1.json
  def update
    respond_to do |format|
      if @cita.update(cita_params)
        format.html { redirect_to @cita, notice: 'Cita was successfully updated.' }
        format.json { render :show, status: :ok, location: @cita }
      else
        format.html { render :edit }
        format.json { render json: @cita.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /citas/1
  # DELETE /citas/1.json
  def destroy
    @cita.estatus = 2
    @cita.save
    respond_to do |format|
      format.html { redirect_to citas_url, notice: 'Cita was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def historial
    @histo = Cita.where({:usuario_id => current_usuario.id, :estatus => [3,4,5]})
  end

  def cancelarCita
    @cita = Cita.find(params[:id])
    @collection_tipo = TipoEventualidad.all
    @collection_motivo = Motivo.all
    @referencia_tipo ="tipo_eventualidad_id"
    @referencia_motivo = "motivo_id"
    @eventualidad = Eventualidad.new

    render "cancelarCitas"
  end

  def confirmarCancelacion
    @cita = Cita.find(params[:cita_id])
    @historialCita = HistorialCita.new(fecha: DateTime.now, estatus_anterior: @cita.estatus, estatus_nuevo: 5, cita:@cita)
    @cita.estatus = 5
    @eventualidad = Eventualidad.new(eventualidad_params)
    @eventualidad.tipo_eventualidad_id = 1
    @eventualidad.fecha_inicio = Date.today()
    @eventualidad.fecha_fin = Date.today()
    @eventualidad.save
    @cita.eventualidad_id = @eventualidad.id
    @cita.save
    @historialCita.save
    redirect_to citas_url
  end

   def cancelar_movil
    @cita = Cita.find(params[:id])
    @cita.estatus = 5
    @eventualidad = Eventualidad.new(:descripcion => 'Cancelada por Movil', :tipo_eventualidad_id => 3, :motivo_id => 4, :fecha_inicio => DateTime.now, :fecha_fin => DateTime.now)
    @eventualidad.tipo_eventualidad_id = 1
    @eventualidad.fecha_inicio = Date.today()
    @eventualidad.fecha_fin = Date.today()
    @eventualidad.save
    @cita.eventualidad_id = @eventualidad.id
    @cita.save
    respond_to do |format|
      format.json {render @cita}
    end
  end

  def chequear
    @citas = Cita.joins(turno: { horario: :servicio } ).where("horarios.servicio_id" => current_usuario.servicio_id ).where(:estatus => 1)
  end

  def chequearCita
    @cita = Cita.find(params[:id])
    @sexos = Sexo.all
    @persona = @cita.persona

    render "chequear_citas"
  end

  def guardarChequearCita
    @cita = Cita.find(params[:cita_id])
    @persona = @cita.persona
    @persona.update(persona_params)
    @cita.estatus = 2
    @cita.save
    @historialCita = HistorialCita.new(fecha: DateTime.now, estatus_anterior: 1, estatus_nuevo: 2, cita:@cita)
    @historialCita.save
    redirect_to "/chequear_cita"
  end

  def finalizar
    @citas = Cita.joins(turno: { horario: :servicio } ).where("horarios.servicio_id" => current_usuario.servicio_id ).where(:estatus => 2)
  end

  def finalizarCita
    @cita = Cita.find(params[:id])
    @persona = @cita.persona
    
    @adicciones = Adiccion.all
    @cirugias = Cirugia.all
    @discapacidades = Discapacidad.all
    @estado_civiles = EstadoCivil.all
    @grupo_sanguineos = GrupoSanguineo.all
    @lesiones = Lesion.all
    @patologias = Patologia.all
    @sexos = Sexo.all
    @vacunas = Vacuna.all
    
    render "finalizar_citas"
  end

  def guardarFinalizarCita
   
    @cita = Cita.find(params[:cita_id])
    @persona = @cita.persona
    @persona.update(persona_params)
    @cita.estatus = 3
    @cita.update(cita_params)
    @cita.save
    @historialCita = HistorialCita.new(fecha: DateTime.now, estatus_anterior: 2, estatus_nuevo: 3, cita:@cita)
    @historialCita.save
    if Configuracion.envia_notificaciones
      Notificacion.create(descripcion:"Evaluacion de cita.", mensaje: "Por favor, envianos tu evaluacion sobre tu cita sobre el servicio "+@cita.turno.horario.servicio.descripcion, url:"", usuario_id:@cita.usuario_id, tipo_notificacion_id: 1, entidad_id: @cita.id )
    end
    redirect_to "/finalizar_cita"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cita
      if Cita.exists?(id: params[:id])
        @cita = Cita.find(params[:id])
      else
        @cita = Cita.new
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cita_params
      params.require(:cita).permit(:turno_id, :persona_id, :usuario_id, :fecha, :tipo_pago_id, :tipo_cita_id, :eventualidad_id, :estatus, :diagnostico)
    end

    def persona_params
      params.require(:persona).permit(:cedula, :nombre, :apellido, :telefono, :direccion, :fecha_nacimiento, :sexo_id, :grupo_sanguineo_id, :estado_civil_id,:altura,:peso)
    end
  def eventualidad_params
    params.require(:eventualidad).permit(:descripcion, :estatus, :tipo_eventualidad_id, :motivo_id, :fecha_inicio, :fecha_fin)
  end
end

app/helpers/citas_helper.rb
module CitasHelper
end

app/views/citas/_form.html.erb
<%= form_for(cita) do |f| %>
  <% if cita.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cita.errors.count, "error") %> prohibited this cita from being saved:</h2>

      <ul>
      <% cita.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :turno_id %>
    <%= f.text_field :turno_id %>
  </div>

  <div class="field">
    <%= f.label :persona_id %>
    <%= f.text_field :persona_id %>
  </div>

  <div class="field">
    <%= f.label :usuario_id %>
    <%= f.text_field :usuario_id %>
  </div>

  <div class="field">
    <%= f.label :fecha %>
    <%= f.datetime_select :fecha %>
  </div>

  <div class="field">
    <%= f.label :tipo_pago_id %>
    <%= f.text_field :tipo_pago_id %>
  </div>



  <div class="field">
    <%= f.label :estatus %>
    <%= f.number_field :estatus %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/citas/cancelar.html.erb
<%= csrf_meta_tag %>
<p id="notice"><%= notice %></p>
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h2 class="parametros-titulo"><%= @citas.new.class.titulo %></h2>
  </div>
</div>
<div class="ibox-content">
  <table class="footable table table-stripped" data-sorting="true" data-filtering="true">
    <thead>
    <tr>
      <th data-breakpoints="xs" data-sorted="true">Cita #</th>
      <th>Servicio</th>
      <th>Especialista</th>
      <th>Paciente</th>
      <th colspan="1"></th>
      <th colspan="1"></th>
    </tr>
    </thead>
    <tbody>
    <% @citas.each do |cita| %>
        <tr>
          <td><%= cita.id%></td>
          <td><%= cita.turno.horario.servicio.tipo_servicio.descripcion %></td>
          <td><%= cita.turno.horario.servicio.especialista.nombre %> </td>
          <td><%= cita.persona.nombre %> <%= cita.persona.apellido%></td>
          <td>
            <%= link_to '', root_path+'cancelar_cita/'+cita.id.to_s, :class => "btn btn-danger btn-sm fa fa-times" %>
        </tr>

    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="5">
        <ul class="pagination pull-right"></ul>
      </td>
    </tr>
    </tfoot>
  </table>
</div>
<br>


<script type="text/javascript">
  $(document).ready(function(){
    $('.table').footable();
  });

</script>

app/views/citas/cancelarCitas.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h2 class="parametros-titulo"><%= "Cancelar cita" %></h2>
      </div>
    </div>
    <div class="ibox-content">
      <%= form_for @eventualidad, :url => '/cancelar_cita', :html => {:class => 'form-horizontal'} do |f| %>
          <% if @eventualidad.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@eventualidad.errors.count, "error") %> prohibited this parametro from being
                  saved:</h2>

                <ul>
                  <% @eventualidad.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>

          <% end %>

          <div class="field form-group">
            <label class="col-lg-2 control-label">Motivo</label>
            <div class="col-lg-10"><%= f.collection_select(:motivo_id, @collection_motivo, :id, :descripcion, {}, :class => "form-control") %></div>
          </div>

          <div class="form-group"><label class="col-lg-2 control-label">Descripción</label>
            <div class="col-lg-10"><%= f.text_field :descripcion, :class => "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
              <%= f.submit 'Guardar', :class => "btn btn-sm btn-white" %>
            </div>
          </div>
          <%= hidden_field_tag :cita_id, @cita.id %>
      <% end %>
    </div>
  </div>
</div>

app/views/citas/chequear.html.erb
<%= csrf_meta_tag %>
<p id="notice"><%= notice %></p>
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h2 class="parametros-titulo"><%= "Recepción de Pacientes" %></h2>
  </div>
</div>
<div class="ibox-content">
  <table class="footable table table-stripped" data-sorting="true" data-filtering="true">
    <thead>
    <tr>
      <th data-breakpoints="xs" data-sorted="true">Fecha</th>
      <th data-breakpoints="xs">Cita #</th>
      <th>Servicio</th>
      <th>Especialista</th>
      <th>Paciente</th>
      <th colspan="1"></th>
    </tr>
    </thead>
    <tbody>
    <% @citas.each do |cita| %>
        <tr>
          <td><%= cita.fecha.strftime("%d/%m/%Y %H:%M %p")%></td>
          <td><%= cita.id%></td>
          <td><%= cita.turno.horario.servicio.descripcion %></td>
          <td><%= cita.turno.horario.servicio.especialista.persona.nombre %> <%= cita.turno.horario.servicio.especialista.persona.apellido %></td>
          <td><%= cita.persona.nombre %> <%= cita.persona.apellido%></td>
          <td>
            <%= link_to 'Confirmar', '/chequear_cita/'+cita.id.to_s, :class => "btn btn-primary btn-sm " %>
        </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="5">
        <ul class="pagination pull-right"></ul>
      </td>
    </tr>
    </tfoot>
  </table>
</div>
<br>


<script type="text/javascript">
  $(document).ready(function(){
    $('.table').footable();
  });

</script>

app/views/citas/edit.html.erb
<h1>Editing Cita</h1>

<%= render 'form', cita: @cita %>

<%= link_to 'Show', @cita %> |
<%= link_to 'Back', citas_path %>

app/views/citas/new.html.erb
<h1>New Cita</h1>

<%= render 'form', cita: @cita %>

<%= link_to 'Back', citas_path %>

app/views/citas/show.html.erb
<div class="row" >
   <div class="col-lg-10 col-lg-offset-1"  id="section-to-print">
   <br>
          <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h2 class="parametros-titulo"><%= "Detalles de la cita" %></h2>
              </div>
          </div>
          <div class="ibox-content container-fluid">
            <div class="row">
              <div class="col-sm-12">
                <div class="field form-group">
                  <h2 class="parametros-titulo form-group"> <%= "Cita #"+@cita.id.to_s %></h2>
                </div>
              </div>
              
            </div>
            <div class="container-fluid" >
              <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#cita">Detalles</a></li>
                <% if @cita.estatus == 4 %>
                  <li><a data-toggle="tab" href="#diagnostico">Diagnóstico</a></li>
                <% else %>
                  <li class="disabled"><a>Diagnóstico</a></li>
                <% end %>
                <% if @cita.estatus == 5 %>
                  <li><a data-toggle="tab" href="#cancelacion">Cancelación</a></li>
                <% else %>
                  <li class="disabled"><a>Cancelación</a></li>
                <% end %>
              </ul>

              <div class="tab-content" >
                <div id="cita" class="tab-pane fade in active">
                  <br><br>


                   <div class="row">
                     
                      <div class="col-lg-12">
                          <div class="ibox float-e-margins">
                              <div class="ibox-content " >
                                  <table class="tabla-horarios table-bordered table-hover" width="100%">
                                      <thead>
                                          <tr>
                                              <th>Nombre y Apellido del Paciente</th>
                                              <th>Cédula</th>
                                              <th>Fecha de Solicitud</th>
                                              <th>Fecha de la Cita</th>
                                              <th>Hora</th>
                                          </tr>
                                      </thead>
                                      <tbody>
                                          <tr>
                                              <td><%= label_tag(:paciente, @cita.persona.nombre+" "+@cita.persona.apellido, {}) %></td>
                                              <td><%= label_tag(:cedula, @cita.persona.cedula, {}) %></td>
                                              <td><%= label_tag(:fecha_solicitud, @cita.created_at.strftime("%d/%m/%Y"), {}) %></td>
                                              <td> <%= label_tag(:fecha, @cita.fecha.strftime("%d/%m/%Y"), {}) %></td>
                                                <td><%= label_tag(:fecha, @cita.fecha.strftime("%H:%M %p "), {}) %></td>
                                          </tr>
                                      </tbody>
                                  </table>
                                  <table table class="tabla-horarios table-bordered table-hover" width="100%">
                                      <thead>
                                          <tr>
                                              <th>Nombre y Apellido del Especialista</th>
                                              <th>Especialidad</th>
                                              <th>Razón de Cita</th>
                                            
                                          </tr>
                                      </thead>
                                      <tbody>
                                          <tr>
                                              <td><%= label_tag(:especialista, @cita.turno.horario.servicio.especialista.nombre, {}) %></td>
                                              <td><%= label_tag(:especialidad, @cita.turno.horario.servicio.tipo_servicio.especialidad.descripcion, {}) %></td>
                                              <td><%= label_tag(:tipo_cita_id, @cita.tipo_cita.descripcion, {}) %></td>
                                            
                                          </tr>
                                      </tbody>
                                  </table >
                                  <table table class="tabla-horarios table-bordered table-hover" width="100%" >
                                      <thead>
                                          <tr>
                                              <th>Dirección de la Clinica</th>
                                          </tr>
                                      </thead>
                                      <tbody>
                                          <tr>
                                              <td>Carrera 28, entre calles 9 y 10, N° 9-124, Concepción, Barquisimeto</td>
                                          </tr>
                                      </tbody>
                                  </table>
                              </div>
                          </div>
                      </div>
              </div>

             
                </div>
                  

                <div id="diagnostico" class="tab-pane fade in">
                <br><br>
                  <div class="row">
                    <div class="col-sm-2">
                      Diagnóstico:
                    </div>
                    <div class="col-sm-10">
                      <%= @cita.diagnostico %>
                    </div>
                  </div>
                </div>

                <div id="cancelacion" class="tab-pane fade in">
                <br><br>
                  <% if !@cita.eventualidad.nil? %>
                    <div class="col-sm-6">
                      <div class="field form-group">
                          <div class="col-lg-6">Fecha de Cancelación:</div>
                          <div class="col-lg-6">
                            <%= label_tag(:fecha_eventualidad, @cita.eventualidad.created_at, {}) %>
                          </div>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="field form-group">
                          <div class="col-lg-6">Motivo:</div>
                          <div class="col-lg-6">
                            <%= label_tag(:motivo_cancelacion, @cita.eventualidad.motivo.descripcion, {}) %>
                          </div>
                      </div>
                    </div>
                  <% end %>
                </div>
            </div>
            
            
          </div>
          <br><br>


 <div class="form-group">
              <div class="col-lg-offset-5 col-lg-2">
                 <%= link_to 'Atrás', citas_path, :class => "btn btn-success btn-sm" %>
              </div>
  
          </div>
  </div>
</div>