config/routes.rb
Myapp::Application.routes.draw do

  resources :plantilla_correos
  resources :configuraciones
  resources :referencias
  get '/mi_horario', to: 'horarios#mi_horario'
  get '/usuarios/registrar', to: 'usuarios#registrar'

  post '/usuarios/guardar', to: 'usuarios#guardar'

  get '/usuarios/editar/:id', to: 'usuarios#editar'

  post '/usuarios/modificar', to: 'usuarios#modificar'

  get '/usuarios/cambiar_clave', to: 'usuarios#cambiar_clave'

  post '/usuarios/cambiar_clave', to: 'usuarios#confirmar_clave'

  delete '/usuarios/eliminar/:id', to: 'usuarios#eliminar'

  get 'grafico/tiempo_atencion'

  post 'grafico/tiempo_atencion', to: 'grafico#generar_tiempo_atencion'

  get 'grafico/tiempo_recepcion'

  post 'grafico/tiempo_recepcion', to: 'grafico#generar_tiempo_recepcion'

  get 'grafico/citas_por_turno'

  post 'grafico/citas_por_turno', to: 'grafico#generar_citas_por_turno'

  get 'grafico/satisfaccion_pacientes'

  post 'grafico/satisfaccion_pacientes', to: 'grafico#generar_satisfaccion_pacientes'

  get 'grafico/citas_solicitadas'

  post 'grafico/citas_solicitadas', to: 'grafico#generar_citas_solicitadas'

  get '/difusiones/update_entidades', to: 'difusiones#update_entidades'

  get '/grafico/update_entidades', to: 'grafico#update_entidades'

  get '/grafico/update_eventos', to: 'grafico#update_eventos'

  get '/grafico/update_servicios', to: 'grafico#update_servicios'

  get '/servicios/update_especialistas', to: 'servicios#update_especialistas'

  get '/grafico/update_servicios_por_especialidad', to: 'grafico#update_servicios_por_especialidad'

  get 'grafico/motivos_cancelacion'

  post 'grafico/motivos_cancelacion', to: 'grafico#generar_motivos_cancelacion'

  resources :suscriptores
  resources :medio_difusiones
  resources :perfiles
  resources :tipo_especialidades
  resources :rango_pesos
  resources :rango_edades
  resources :difusiones
  resources :tipo_entidades
  resources :parentescos
  resources :tipo_parentescos
  resources :tipo_difusiones

  post 'usuarios/create', to: 'usuarios#create'

get 'tipo_servicios/filtrar', to: 'tipo_servicios#filtrar'
  get 'perfil', to: 'usuarios#perfil'

  post 'perfil', to: 'usuarios#actualizarPerfil'

  get 'disponibilidad', to: 'horarios#disponibilidad'

  match '/search', to: "personas#search", via: "post"
  match 'grafico/calificaciones_por_criterio', to: "grafico#generar_citas_evaluadas", via: "post"
  match 'grafico/calificaciones_por_especialidad', to: "grafico#calcular_calificaciones_por_especialidad", via: "post"
  match 'grafico/citas_por_evento', to: "grafico#calcular_citas_por_evento", via: "post"
  match 'grafico/citas_por_difusion', to: "grafico#calcular_citas_por_difusion", via: "post"
  match 'grafico/calificaciones_por_servicio', to: "grafico#calcular_calificaciones_por_servicio", via: "post"
  match 'grafico/citas_por_turno', to: "grafico#generar_citas_por_turno", via: "post"
  match 'grafico/satisfaccion_pacientes', to: "grafico#generar_satisfaccion_pacientes", via: "post"
  match 'grafico/citas_por_caracteristicas', to: "grafico#generar_citas_caracteristicas", via: "post"

  get 'grafico/generar'

  get 'grafico/citas_por_especialidad'

  get 'grafico/criterios_servicio'

  get 'grafico/citas_por_turno'

  get 'grafico/reporte_por_criterios'
  get 'grafico/calificaciones_por_criterio'
  get 'grafico/calificaciones_por_especialidad'
  get 'grafico/citas_por_evento'
  get 'grafico/citas_por_difusion'
  get 'grafico/calificaciones_por_servicio'
  get 'grafico/citas_por_caracteristicas'

  get 'agenda_servicio/', to: 'agenda_servicio#lista'

  get 'historial_cita', to: 'citas#historial'

  get 'cancelar_cita', to: 'citas#cancelar'
  get 'cancelar_cita/:id', to: 'citas#cancelarCita'
  post 'cancelar_cita', to: 'citas#confirmarCancelacion'

  put 'cancelar_movil/:id', to: 'citas#cancelar_movil'

  get 'chequear_cita', to: 'citas#chequear'
  get 'chequear_cita/:id', to: 'citas#chequearCita'
  post 'chequear_cita', to: 'citas#guardarChequearCita'

  get 'finalizar_cita', to: 'citas#finalizar'
  get 'finalizar_cita/:id', to: 'citas#finalizarCita'
  post 'finalizar_cita', to: 'citas#guardarFinalizarCita'

  get 'historico', to: 'bd_admins#historico'
  post 'finalizar_migracion', to: 'bd_admins#cambiarInformacion'

  get 'guardarback', to: 'bd_admins#guardarback'
  post 'guardarback', to: 'bd_admins#guardarback'

  get 'restauracion', to: 'bd_admins#restauration'
  post 'restauracion', to: 'bd_admins#restauration'

  get 'evaluar_cita/:id', to: 'evaluaciones#evaluarCita', as: "evaluar_cita"
  resources :tipo_turnos

  get 'cerrar_turno/:id', to: 'horarios#cerrar_turno'

  resources :informacion_generals
  resources :noticias
  resources :opiniones
  resources :tipo_opiniones
  resources :tipo_preguntas
  resources :tipo_noticias
  get 'usuarios', to: 'usuarios#index'
  get 'solicitante/:id', to: 'usuarios#solicitante'

  get 'agenda_servicio/:id/detalle', to: 'agenda_servicio#detalle', as: :agenda_servicio_detalle

  resources :notificaciones
  resources :tipo_notificaciones
  resources :servicio_eventos
  resources :tipo_preguntas
  resources :tipo_opiniones
  resources :tipo_noticias
  resources :preguntas
  resources :opiniones
  resources :noticias
  resources :universidades
  resources :formacion_academicas
  resources :nivel_formaciones
  resources :eventos
  resources :tipo_eventos
  resources :busquedas
  resources :tipo_busquedas
  resources :categorias
  resources :citas
  resources :evaluaciones
  resources :criterio_tipo_servicios
  resources :calificaciones
  resources :criterios
  resources :servicios
  resources :sexos
  resources :personas
  resources :roles
  devise_for :usuarios , :controllers => {registrations: "usuarios/registrations", sessions: "usuarios/sessions", confirmations: 'usuarios/confirmations'}

  devise_scope :usuario do
    get 'login', to: 'usuarios/sessions#new'

    authenticated :usuario do
      root to: 'home#index', as: :authenticated_root
    end

  end
  get 'login_movil', to: 'usuarios#login_movil'
  get 'login_web', to: 'usuarios#login_web'
  get 'encontrar_usuario', to: 'usuarios#encontrar_por_email'

  root to: 'usuarios/sessions#new'

  resources :eventualidades
  resources :turnos
  resources :horarios
  resources :dias
  resources :tipo_criterios
  resources :tipo_horarios
  resources :tipo_citas
  resources :tipo_criterio
  resources :tipo_calificaciones
  resources :tipo_evaluaciones
  resources :tipo_pagos
  resources :tipo_eventualidades
  resources :motivos
  resources :tipo_motivos
  resources :tipo_servicios
  resources :tipo_atenciones
  resources :especialistas
  resources :especialidades
  resources :ubicaciones
  resources :sectores
  resources :sectors
  resources :tipo_ubicaciones
  resources :ciudades
  resources :estados
  resources :paises
  resources :discapacidades
  resources :tipo_discapacidades
  resources :patologias
  resources :tipo_patologias
  resources :vacunas
  resources :adicciones
  resources :tipo_adicciones
  resources :grupo_sanguineos
  resources :cirugias
  resources :tipo_cirugias
  resources :estado_civiles
  resources :ocupaciones
  resources :profesiones
  resources :lesiones
  resources :tipo_lesiones
  resources :habitos
  resources :tipo_habitos
  resources :option_menus

  get "home/index"
  get "home/minor"

  resources :preguntas
  resources :encuestas
end

app/models/estado.rb
class Estado < ApplicationRecord
  belongs_to :pais
  has_many :ciudad, dependent: :destroy

  def tipo
  	return self.pais
  end

  def self.titulo
	  return "Estado"
  end

end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @tipo = Pais.titulo
    @parametros = Estado.where(:estatus => 1)
     respond_to do |format|
      format.html {  render "parametros_select/index" }
      format.json { render json: @parametros }
    end
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
    @parametro = Estado.find(params[:id])

    #render "parametros_select/edit"
  end

  # GET /estados/new
  def new
    @parametro = Estado.new
    @collection = Pais.where(:estatus => 1)
    @referencia = :pais_id
    @estado = Estado.new
    render "parametros_select/new"
  end

  # GET /estados/1/edit
  def edit
    @parametro = Estado.find(params[:id])
    @collection = Pais.where(:estatus => 1)
    @referencia = :pais_id
    @estado = Estado.new
    render "parametros_select/edit"
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to estados_path, notice: 'El registro ha sido creado exitosamente.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to estados_path, info: 'El registro ha sido actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.estatus = 2
    @estado.save
    respond_to do |format|
      format.html { redirect_to estados_path, alert: 'El registro ha sido eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:descripcion, :estatus, :pais_id)
    end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/views/estados/_form.html.erb
<%= form_for(estado) do |f| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_field :descripcion %>
  </div>

  <div class="field">
    <%= f.label :estatus %>
    <%= f.number_field :estatus %>
  </div>

  <div class="field">
    <%= f.label :pais_id %>
    <%= f.text_field :pais_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h2 class="parametros-titulo"><%= @parametro.class.titulo %></h2>
      </div>
    </div>
    <div class="ibox-content">
      <%= form_for @parametro, :html => {:class => 'form-horizontal'} do |f| %>
          <% if @parametro.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@parametro.errors.count, "error") %> prohibited this parametro from being saved:</h2>

                <ul>
                  <% @parametro.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="field form-group">
            <label class="col-lg-2 control-label">País</label>

            <div class="col-lg-10">
              <%= f.collection_select(@referencia, @collection, :id, :descripcion, {:prompt => "Seleccione"}, {:class => "form-control"}) %>
            </div>

          </div>

          <div class="form-group"><label class="col-lg-2 control-label">Descripcion</label>

            <div class="col-lg-10"><%= f.text_field :descripcion, :class => "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-lg-offset-3 col-lg-2">
              <%= f.submit "Guardar", :class => "btn btn-sm btn-primary" %>
            </div>
            <% if (@parametro.new_record?) %>
                <div class="col-lg-2">
                  <%= link_to 'Limpiar', '', type: :reset, :class => "btn btn-sm btn-warning" %>
                </div>
            <% end %>
            <div class="col-lg-2">
              <%= link_to 'Atras', polymorphic_url(@parametro.class), :class => "btn btn-sm btn-success " %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/estados/index.html.erb
<%= csrf_meta_tag %>
<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h2 class="parametros-titulo"><%= @parametros.new.class.titulo %></h2>
  </div>
</div>
<div class="ibox-content">
  <%= link_to "Registrar", new_polymorphic_url(@parametros.new), :class => "btn btn-primary btn-sm"%>
  <br><br>
  <table class="footable table table-stripped" data-sorting="true" data-filtering="true">
    <thead>
    <tr>
      <th data-breakpoints="xs" data-sorted="true">País</th>
      <th>Descripción</th>
      <th colspan="1"></th>
    </tr>
    </thead>
    <tbody>
    <% @parametros.each do |parametro| %>
        <tr>
          <td><%= parametro.tipo.descripcion %></td>
          <td><%= link_to parametro.descripcion, edit_polymorphic_url(parametro) %></td>
          <td>
            <%= link_to 'Editar', edit_polymorphic_url(parametro), :class => "btn btn-warning btn-sm " %>
            <%= link_to 'Eliminar', polymorphic_url(parametro), :method => :delete, data: { confirm: '¿Está seguro que desea eliminar el estado?' } , :class => "btn btn-danger btn-sm"%></td>
        </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="5">
        <ul class="pagination pull-right"></ul>
      </td>
    </tr>
    </tfoot>
  </table>
</div>
<br>


<script type="text/javascript">
  $(document).ready(function(){
    $('.table').footable();
  });

</script>

app/views/estados/new.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h2 class="parametros-titulo"><%= @parametro.class.titulo %></h2>
      </div>
    </div>
    <div class="ibox-content">
      <%= form_for @parametro, :html => {:class => 'form-horizontal'} do |f| %>
          <% if @parametro.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@parametro.errors.count, "error") %> prohibited this parametro from being saved:</h2>

                <ul>
                  <% @parametro.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="field form-group">
            <label class="col-lg-2 control-label">País</label>

            <div class="col-lg-10">
              <%= f.collection_select(@referencia, @collection, :id, :descripcion, {:prompt => "Seleccione"}, {:class => "form-control"}) %>
            </div>

          </div>

          <div class="form-group"><label class="col-lg-2 control-label">Descripcion</label>

            <div class="col-lg-10"><%= f.text_field :descripcion, :class => "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-lg-offset-3 col-lg-2">
              <%= f.submit "Guardar", :class => "btn btn-sm btn-primary" %>
            </div>
            <% if (@parametro.new_record?) %>
                <div class="col-lg-2">
                  <%= link_to 'Limpiar', '', type: :reset, :class => "btn btn-sm btn-warning" %>
                </div>
            <% end %>
            <div class="col-lg-2">
              <%= link_to 'Atras', polymorphic_url(@parametro.class), :class => "btn btn-sm btn-success " %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @estado.descripcion %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @estado.estatus %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @estado.pais %>
</p>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>